version: '3'

services:
  flaskapp:
    build: ./flaskapp
    container_name: flaskapp
    ports:
      - "5000:5000"
#    restart: always

  nodeapp:
    build: ./nodeapp
    container_name: nodeapp
    ports:
      - "3000:3000"
#    restart: always
